More bugfixes

diff --git a/slacker b/slacker
--- a/slacker
+++ b/slacker
@@ -1,7 +1,8 @@
 #!/bin/bash
-# slacker : A package manager for slackbuilds repository
+# slacker : A package manager for slackbuilds repository.
 ##
 # Copyright (C) 2014 Aaditya Bagga <aaditya_gnulinux@zoho.com>
+  ver="0.2"
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -60,9 +61,16 @@ get-package () {
 }
 check-option () {
 	if [ ! "$1" ]; then
-		echo "Additional parameter required for this option. Type slacker -h for more info."
+		echo "Additional parameter(s) required for this option. Type slacker -h for more info."
+		exit 1
 	fi
 }
+
+# Check no of input parameters
+if [ $# -gt 3 ] ; then
+	echo "Invalid Syntax. Type slacker -h for more info."
+	exit 1
+fi
 
 # Options
 case "$1" in
@@ -168,9 +176,11 @@ query|-q)
 	git --git-dir="$gitdir" pull origin master ;;
 --all|-a)
 	find "$repo" -type d -maxdepth 2 -mindepth 1 | less ;;
+--version)
+        echo -e "slacker, a package manager for slackbuilds repository. ver-$ver" ;;
 --help|-h|*)
 	echo -e "Usage: slacker <option> [package]\nOptions-"
-	echo -e "[search,-s]\t[info,-i]\t[readme,-r]\n[goto,-g]\t[view,-v]\t[list,-l]\n[desc,-d]\t[get,-G]\t[build,-B]\n[install,-I]\t[upgrade,-U]\t[remove,-R]\n[query,-q]\t[--update,-u]\t[--all,-a]\n[--help,-h]\n"
+	echo -e "[search,-s]\t[info,-i]\t[readme,-r]\n[goto,-g]\t[view,-v]\t[list,-l]\n[desc,-d]\t[get,-G]\t[build,-B]\n[install,-I]\t[upgrade,-U]\t[remove,-R]\n[query,-q]\t[--update,-u]\t[--all,-a]\n[--help,-h]\t[--version|-v]\n"
        echo "For more info, see the README." ;;
 esac
 
